[package]
name = "ProjectEuler_0104"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"

[[bin]]
name = "ProjectEuler_0104"
path = "main.rs"
